name: app_day
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar_2: ^5.0.3
  hive: ^2.2.3
  carousel_slider: ^5.0.0
  flutter_riverpod: ^2.6.1
  hive_flutter: ^1.1.0
#  local_auth: ^2.3.0
  easy_localization: ^3.0.7
#  google_maps_flutter: ^2.9.0
#  location: ^7.0.0
#  geocoding: ^3.0.0
#  geolocator: ^12.0.0
#  custom_info_window: ^1.0.1
#  intl: ^0.19.0
#  maps_launcher: ^2.2.1

#  image_picker: ^1.1.2
#  story_view: ^0.16.5
#  web_socket_channel: ^3.0.1

#  face_camera: ^0.1.4
#  flutter_screen_lock: ^9.1.0
#  dio: ^5.7.0
#  flutter_widget_from_html: ^0.15.2
#  local_captcha: ^1.0.4
#  flutter_staggered_animations: ^1.1.1
#  shimmer: ^3.0.0
#  loading_animation_widget: ^1.3.0
#  url_launcher: ^6.3.1
#  photo_view: ^0.15.0
#  flutter_pw_validator: ^1.6.0

#  file_picker: ^8.1.3
  connection_notifier: ^2.0.1
#  webviewx_plus: ^0.5.0
#  permission_handler: ^11.3.1
#  flutter_local_notifications: ^18.0.1
#  webview_flutter: ^4.10.0
#  animations: ^2.0.11
#  ntp: ^2.0.0
#  chat_bubbles: ^1.6.0
#  widget_loading: ^0.4.0
#  timeline_tile: ^2.0.0
#  flutter_easy_animations: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - assets/fonts/

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
          weight: 600
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-VariableFont_wght.ttf

  # see https://flutter.dev/custom-fonts/#from-packages