name: app_day
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+5

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar_2: ^5.0.3
  hive: ^2.2.3
  carousel_slider: ^5.0.0
  flutter_riverpod: ^2.6.1
  hive_flutter: ^1.1.0
  easy_localization: ^3.0.7
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  connection_notifier: ^2.0.1
  flutter_widget_from_html_core: ^0.15.2
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  dartz:
#  photo_view: ^0.15.0
  loading_indicator: ^3.1.1
  fade_shimmer: ^2.3.0
  custom_refresh_indicator: ^4.0.1
  local_captcha: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - assets/fonts/
    - lib/core/hive_saved/hive_saved.dart

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
          weight: 600
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-VariableFont_wght.ttf

  # see https://flutter.dev/custom-fonts/#from-packages